# Generated by Django 4.0 on 2021-12-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('Titel', models.TextField(max_length=100)),
                ('summary', models.CharField(max_length=500)),
            ],
        ),
    ]
